### ISSUE TITLE
Enum utilities

### ISSUE THREAD

**Issue by TheKingOfAtlantis** [TheKingOfAtlantis/Enigma-old#18]
- [x] Join/Union of enums
 - [x] Remove/Intersection of enums
 - [x] Convert to/from scoped enums
 - [x] Enum querying

**Comment by TheKingOfAtlantis** [comment]
Primarily we need tests to ensure that these enum utility functions work as advertised

May need to look into alternative for template vararg, as this will generate many instances of the various enum utility functions, maybe replace with `std::vector` or a regular vararg function rather than template vararg.

May need to investigate this a bit

**Todo**
 - [x] Tests needed
 - [x] Investigate alternatives

**Comment by TheKingOfAtlantis** [comment]
Missing tests for the query functions:
 - [x] Test for `hasFlag(...)`
 - [x] Test for `hasAll(...)`
 - [x] Test for `hasAny(...)`

**Comment by TheKingOfAtlantis** [comment]
Test have been written and do pass
Although they occasionally fail simply due to nature of the test (due to false positives)
